services:
  padariaapp:
    container_name: padariaapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./padariaapp:/padariaapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql2
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env